## Global varibles
Every Entity (Table) most have its own Data, Model and Controller.
Those files have to be named as **EntityName**

```cs
EntityName = "Users"

// Model will be called in singular (From Users to User)
ModelName = "User" //$EntityName 
ControllerName = $"{EntityName}Controller" 
DatabaseName="edfa123a8d3561"
```
## Create MySql database (optional)
First you can create a MySql database to work with.

## 1- Create a new solution with an mvc project 
This is in Shell scripts folder

## 2- Create the controler
Do this inside your mvc project

```bash
## touch Controllers/<CONTROLLER NAME>Controller.cs 
touch Controllers/UsersController.cs

```

## 3- Create a model

Pay attention, only use singular in model

```bash
## touch Models/<Model NAME>.cs 
touch Models/User.cs

```

## 4- Create views folder
```bash
mkdir Views/Users

```

## 5- Create basic controller structure
```csharp
using Microsoft.AspNetCore.Mvc;

// Dont forget plural in Controllers
// namespace <ROOT FOLDER>
namespace Products.Mvc.Controllers
{
  // Class most match with file name
  public class UserController : Controller
  {

  }
}
```

## 6- Create basic model structure
```cs
namespace Products.Mvc.Models
{
  public class User
  {

  }
}
```

## 7- Install Microsoft.EntityFrameworkCore
```bash
dotnet add package Microsoft.EntityFrameworkCore
```

Your .csproj should pass from
```cs
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```

To
```cs
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.3" />
  </ItemGroup>

</Project>
```


## What is Entity Framework Core?
This is a description from microsoft

> Entity Framework (EF) Core is a lightweight, extensible, open source and cross-platform version of the popular Entity Framework data access technology.
>
> EF Core can serve as an object-relational mapper (O/RM), which:
>  - Enables .NET developers to work with a database using .NET objects.
>  - Eliminates the need for most of the data-access code that typically needs to be written.
>
> EF Core supports many database engines, see Database Providers for details.

Basically EF Core is used to connect database engines and interact with them, it allow to make CRUD operations with entities in database

**References**

Microsoft.(2024). Entity Framework Core
https://learn.microsoft.com/en-us/ef/core/ 

## 8- Create connection to data base
The file inside data, have to be named as database name

```bash
mkdir Data

## touch <DATABASE NAME>Context
## In our case $databaseName is autogenerated by server, so we use a generic name, in this case Base
touch Data/BaseContext.cs
```

## 9- Create basic Data structure

```cs
// BaseContext.cs

using Microsoft.EntityFrameworkCore;
// namespace <ROOT NAME>
namespace Products.Mvc.Data
{
  // Match file name
  public class BaseContext : DbContext
  {

  }
}
```

## What is DbContext class?
DbContext class create the connection of the database between server and MySql, this is made
with the configuration of key `ConnnectionStrings` in `appsettings.json` 

```json
// appsettings.json
"ConnectionStrings": 
{
  "MySqlConnection": "server=clever-cloud.com;port=3306;database=dasd22sj42u21bd61;Uid=82jdu295foa81;password=KDndsa241As1s2"
}
```

## 10- Add constructor in Data BaseContext

Constructor param require and object of type DBContextOptions< BaseContext >. This is use for Entity Framework to setup options in DBContext 

```cs
using Microsoft.EntityFrameworkCore;
// namespace <ROOT NAME>
namespace Products.Mvc.Data
{
  // Match file name
  public class BaseContext : DbContext
  {
    /* 
    CODE EXPLAIN
    
    1- First you call BaseContext Contructor (public BaseContext)
    2- Call a generic DBContextOptions (DBContextOptions<BaseContext> <ALIAS>)
    3- Use an alias for "DBContextOptions<BaseContext>" in this case options (DBContextOptions<BaseContext> options)
    4- Call parent constructor (base (options))
    */

    public BaseContext(DbContextOptions<BaseContext> options) : base (options)
    {

    }
  }
}
```

**References**
Microsoft.(2024). DbContextOptions versus DbContextOptions< TContext >
https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#dbcontextoptions-versus-dbcontextoptionstcontext

Microsoft.(2024). Constraints on type parameters (C# Programming Guide)
https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters

Microsoft.(2024). base - Parent constructor
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/base

## 11- Create model base in entity
You create the structure of model base in database attributes (keys)

```cs
// Models/User.cs
namespace Products.Mvc.Models
{
  // You create the structure base in database attributes
  public class User
  {
    // Get / Set are used to allow reading (get) and writing (set)
    public int Id {get; set;}
    public string Name {get; set;}
    public string Lastname {get; set;}
    public string Email {get; set;}
  }
}
```

## 12- Register model in database context
entity = table in database
DBSet is use to convert an entity in a collection, it means create a collection structure
base in entity attributes, DBset allow to use database entity as a model.

```cs
// Remember it is a connection between database and model
using Microsoft.EntityFrameworkCore;

// Reference model directory
using Products.Mvc.Models;

// namespace <ROOT NAME>
namespace Products.Mvc.Data
{
  //Match file name
  public class BaseContext : DbContext
  {
    /* 
    CODE EXPLAIN
    
    1- First you call BaseContext Contructor (public BaseContext)
    2- Call a generic DBContextOptions (DBContextOptions<BaseContext> <ALIAS>)
    3- Use an alias for "DBContextOptions<BaseContext>" in this case options
    4- Call parent constructor (base (options))
    */

    public BaseContext(DbContextOptions<BaseContext> options) : base (options)
    { }

    // Register model
    // DBSet = set database
    // DBSet<MODEL> <DATABASE TABLE>
    public DbSet<User> Users {get; set;}

  }
}
```

**References**
stackoverflow.(2012). About DbSet and DbContext 
https://stackoverflow.com/questions/13627829/about-dbset-and-dbcontext

## 13- Create reference of databaseContext in controller
1- Had a connection between model and databaseContext, where we convert an entity to
an MVC model
2- Connect databaseContext to controller  

```cs
using Products.Mvc.Data;
using Microsoft.AspNetCore.Mvc;

// Dont forget plural in Controllers
// namespace <ROOT FOLDER>
namespace Products.Mvc.Controllers
{
  public class UserController : Controller
  {
    // Readonly just allow to be modified inside a constructor
    public readonly BaseContext _context;

    /* This constructor reference a database, it is not using a entity, just making the
    connection */  
    // Basecontext is automatically setup, you don't have to pass a value
    public UserController(BaseContext context)
    {
      _context = context;
    }
  }
}
```

## What (_) mean in _context
if with define a varible with "_" with refering to a class member, it makes easier to identify
a class member.

A local variable is the variable you declare in a function. Its lifespan is on that Function only. 
A member variable is the variable you declare in a class definition. Its lifespan is inside that class only.
It is Global Variable. It can be access by any function inside that same class.

## 14- Making the connection between model an database

```cs
using Products.Mvc.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// Dont forget plural in Controllers
// namespace <ROOT FOLDER>
namespace Products.Mvc.Controllers
{
  public class UserController : Controller
  {
    // Readonly just allow to be modified inside a constructor
    public readonly BaseContext _context;

    /* This constructor reference a database, it is not using a entity, just making the
    connection */  
    // Basecontext is automatically setup, you don't have to pass a value
    public UserController(BaseContext context)
    {
      _context = context;
    }

    public async Task<IActionResult> Index ()
    {
      
      // return View(await _context.Users.ToListAsync()); == <DATABASE> <MODEL> <select *>
      return View(await _context.Users.ToListAsync());
      // SELECT * FROM Users
    }
  }
}
```

## 15- Add MySql database provider (Pomelo)
`dotnet add package Pomelo.EntityFrameworkCore.MySql`

Your `.csproj` should look like this
```cs
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.3" />
    // Here is Pomelo installed
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
  </ItemGroup>

</Project>
```

**References**

Microsoft. (2024). Adding a database provider to your application </br>
https://learn.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli#adding-a-database-provider-to-your-application

## 16- Register MySql as a service in Program.cs
```cs
using Microsoft.EntityFrameworkCore;
using Products.Mvc.Data;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllersWithViews();

// Personal service
builder.Services.AddDbContext<BaseContext> ( options => 
    options.UseMySql
    (
      // builder.Configuration.GetConnectionString("MySqlConnection"),
      builder.Configuration.GetConnectionString("MySqlConnection"),
      Microsoft.EntityFrameworkCore.ServerVersion.Parse("8.0.20-mysql")
    )
);

var app = builder.Build();

// More code ...
```

**References**
Microsoft.(2024). Program.cs 
https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-8.0&tabs=visual-studio#programcs

## 17- Add connection to appsettings.json
This will be used for DbContext

Remember that the connection key, must match with Program

```json
// appsettings.json
"ConnectionStrings": 
{
  // Have to match with program (getConnectionString)
  "MySqlConnection": "server=clever-cloud.com;port=3306;database=dasd22sj42u21bd61;Uid=82jdu295foa81;password=KDndsa241As1s2"
}
```
